### ISSUE TITLE
[Feature]: Implementation of static pages

### ISSUE THREAD

**Issue by Michaeldrm** [vuestorefront/vendure#121]
### How the project can be improved?

As with any other online store, it is essential to have static pages for the contact page, terms of use, privacy policy, among others.

### What are the acceptance criteria?

- [ ]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Baroshem** [comment]
Hi @Michaeldrm 

This is indeed a useful feature but it is out of the scope of our regular integration scope. When building integrations for Vue Storefront we are following certain approach so that all integrations work and look very similar. So in our Core framework we do not have these static pages implemented yet.

However, I will add this feature for 1.1.0 milestone as it may be useful to have this in the stable version with first minor update.

**Comment by Michaeldrm** [comment]
Hi @Baroshem 

I've already added this functionality in my local version and I can help with this, but I confess that I'm not the best or most suitable to do it as I do these things as a hobby and I'm still learning. Let me know if you need any help.

**Comment by Baroshem** [comment]
@Michaeldrm 

It would be awesome if you could propose a solution that you have already developed. Then we can review how does it fit in the overall Vue Storefront approach so that we can adjust it and have it as a part of 1.1.0 version :)

You can fork the repo and add your changes to the theme folder to see how they fit the integration and then create a pull request so than I can take a look at it.

BTW, we are all learning 😃

**Comment by Michaeldrm** [comment]
Excellent! I'll do it today! Thanks.
